development: &non_production_settings
  site_url: http://bandofstrangers.local
  site_name: BandofStrangers
  admin_email: elton.stewart@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://bandofstrangers.heroku.com
  site_name: BandofStrangers
  admin_email: elton.stewart@gmail.com  
  
production:
  site_url: http://bandofstrangers.heroku.com
  site_name: BandofStrangers
  admin_email: elton.stewart@gmail.com
